-- Edu.sistem Pro IA 2.2 - esquema opcional para Supabase
-- Ejecutar en el SQL Editor de Supabase si querés activar cuentas persistentes.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  plan text not null default 'gratis' check (plan in ('gratis','docente','profesional','institucion')),
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  action text not null default 'generation',
  created_at timestamptz not null default now()
);

create index if not exists usage_events_user_created_idx
  on public.usage_events(user_id, created_at);

alter table public.profiles enable row level security;
alter table public.usage_events enable row level security;

-- Las políticas deben ajustarse a la estrategia comercial elegida.
-- No se habilitan políticas amplias automáticamente.
